language: c
 
install:
  - sudo apt-get install mono-devel mono-gmcs nunit nunit-console
 
script:
  - mkdir build
  - mkdir build/release
  - mkdir build/test
  - echo 'updating version.cs'
  - rm Version.cs
  - BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
  - BUILD_VERSION=0.1.$BUILD_NUMBER.0
  - VERSION_CS="partial class AssemblyInfo { public const string Version = \"$BUILD_VERSION\"; }"
  - echo $VERSION_CS >> Version.cs
  - cat Version.cs
  - echo 'compiling xserializer assembly'
  - MCS_COMMON_OPTS=/target:library /r:System,System.Core,System.Xml,System.Xml.Linq /optimize+ /recurse:*.cs
  - gmcs $MCS_COMMON_OPTS -pkg:nunit /define:NUNIT -out:build/test/XSerializerWithTests.dll
  - gmcs $MCS_COMMON_OPTS -out:build/release/TsvBits.XSerializer.dll
  - nunit-console ./build/test/XSerializerWithTests.dll
  - echo 'building nuget package'
  - SED_ARG=s/VERSION/$BUILD_VERSION/
  - sed $SED_ARG XSerializer.nuspec.template > XSerializer.nuspec
  - cat XSerializer.nuspec
  - wget -O .nuget/Microsoft.Build.dll https://dl.dropbox.com/u/103746479/Microsoft.Build.dll
  - mozroots --import --sync
  - bash nuget pack XSerializer.nuspec

