language: c
 
install:
  - sudo apt-get install mono-devel mono-gmcs nunit nunit-console
 
script:
  - mkdir build
  - gmcs /target:library /r:System,System.Core,System.Xml,System.Xml.Linq -pkg:nunit /define:NUNIT /optimize+ /recurse:*.cs -out:build/XSerializerWithTests.dll
  - gmcs /target:library /r:System,System.Core,System.Xml,System.Xml.Linq /optimize+ /recurse:*.cs -out:build/TsvBits.XSerializer.dll
  - nunit-console build/XSerializerWithTests.dll