language: c
 
install:
  - sudo apt-get install mono-devel mono-gmcs nunit nunit-console
 
script:
  - gmcs /r:System /r:System.Core /r:System.Xml /r:System.Xml.Linq -pkg:nunit /define:NUNIT /optimize+ /recurse:*.cs -out:XSerializerWithTests.dll
  - gmcs /r:System /r:System.Core /r:System.Xml /r:System.Xml.Linq /optimize+ /recurse:*.cs -out:TsvBits.XSerializer.dll
  - nunit-console XSerializerWithTests.dll