language: c
 
install:
  - sudo apt-get install mono-devel mono-gmcs nunit nunit-console
 
script:
  - wget http://launchpad.net/nunitv2/2.5/2.5.10/+download/NUnit-2.5.10.11092.zip
  - unzip NUnit-2.5.10.11092.zip
  - mkdir build/travis
  - copy NUnit-2.5.10.11092/bin/net-2.0/framework/nunit.framework.dll build/travis/nunit.framework.dll
  - xbuild travis.build
  - nunit-console ./build/travis/XSerializerWithTests.dll