language: c
 
install:
  - sudo apt-get install mono-devel mono-gmcs nunit nunit-console
 
script:
  - wget http://launchpad.net/nunitv2/2.6.2/2.6.2/+download/NUnit-2.6.2.zip
  - unzip NUnit-2.6.2.zip
  - xbuild travis.build
  - nunit-console ./build/travis/XSerializerWithTests.dll